apiVersion: v1
kind: Service
metadata:
  name: gateway-svc
  namespace: gateway
spec:
  selector:
    app: gateway-svc
  ports:
    - port: 5040
      targetPort: 5040
      nodePort: 30040
  type: NodePort
